global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: vpn_01
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.97:9091']
  - job_name: vpn_02
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.98:9091']
