{
 "title": "db1000n",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(sum by (status,country)(rate(db1000n_http_request_total{}[5m])))"
    }
   ]
  },
  {
   "title": "Total Packetgen Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum by (status,country)(rate(db1000n_packetgen_total{}[5m])))"
    }
   ]
  },
  {
   "title": "Total Rawnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum by (status,job)(rate(db1000n_rawnet_total{}[5m])))"
    }
   ]
  },
  {
   "title": "Total Slowloris",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(sum by (status,job)(rate(db1000n_slowloris_total{}[5m])))"
    }
   ]
  },
  {
   "title": "Total DNS Blast Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(sum by (status,job)(rate(db1000n_dns_blast_total{}[5m])))"
    }
   ]
  },
  { "title": "Http Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "(sum by (status)(rate(db1000n_http_request_total{}[5m])))"
    }
   ]
  },
  {
   "title": "Successful Requests by Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(db1000n_http_request_total{status=\"success\"}[1m])"
    }
   ]
  },
  {
   "title": "Failed Requests by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "(sum by (destination_host)(rate(db1000n_http_request_total{status=\"fail\"}[5m])))"
    }
   ]
  }
 ]
}